default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 123456

development:
  <<: *default
  database: divinesky_development

test:
  <<: *default
  database: divinesky_test

production:
  <<: *default
  database: divinesky_development
